- name: Install dotfiles
  hosts: localhost
  gather_facts: yes
  become: yes
  become_method: enable
  vars:
    vim_dir: "{{ ansible_env.HOME }}/myvimrc"

  tasks:
    - name: "Download rust"
      shell: "curl --proto =https --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/install_rust.sh"

    - name: "Install rust"
      shell: "sh /tmp/install_rust.sh -y"

    - name: "Install z"
      get_url:
          url: "https://raw.githubusercontent.com/rupa/z/master/z.sh"
          dest: "{{ ansible_env.HOME }}/z.sh"
      tags:
          - z

    - name: "Clone vundle"
      git:
        repo: "https://github.com/VundleVim/Vundle.vim.git"
        dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

    - name: "Clone fzf"
      git:
        repo: "https://github.com/junegunn/fzf.git"
        dest: "{{ ansible_env.HOME }}/.fzf"
        depth: 1
      tags:
          - fzf

    - name: "Install fzf"
      shell: "{{ ansible_env.HOME }}/.fzf/install"
      tags:
          - fzf

    - name: "Install bat"
      shell: "cargo install bat"
      tags: 
        - cargo

    - name: "Clone forgit"
      git:
        repo: "https://github.com/wfxr/forgit.git"
        dest: "{{ ansible_env.HOME }}/.forgit.git"
      tags:
          - forgit

    - name: "Install packages"
      package: 
        name:
          - zsh
          - cmatrix
          # - nodejs
          # Needed for copying to the clipboard
          - vim-gtk
          - ripgrep
        state: present
      become: yes
      tags: 
        - packages
    - name: "Symlink files"
      file:
          src: "{{ item.path  }}"
          dest: "{{ item.dest  }}"
          state: link

      with_items:
          # - { path: '{{ vim_dir  }}/vimrc', dest: '{{ ansible_env.HOME }}/.vimrc' }
          - { path: '{{ vim_dir  }}/.zshrc', dest: '{{ ansible_env.HOME }}/.zshrc' }
          - { path: '{{ vim_dir }}/.fzf_config.sh', dest: '{{ ansible_env.HOME }}/.fzf_config.sh' }
          # - { path: '{{ vim_dir }}/.vim_runtime', dest: '{{ ansible_env.HOME }}/.vim_runtime' }
          # - { path: '{{ vim_dir }}/.tmux', dest: '{{ ansible_env.HOME }}/.tmux' }
          # - { path: '{{ vim_dir }}/tmux.conf', dest: '{{ ansible_env.HOME }}/tmux.conf' }
          # - { path: '{{ vim_dir }}/colors', dest: '{{ ansible_env.HOME }}/colors' }
          - { path: '{{ vim_dir }}/aliases', dest: '{{ ansible_env.HOME }}/.aliases' }
      tags: 
        - symlinks
