  
set nocompatible
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" 
" Plugin 'MarcWeber/vim-addon-mw-utils'
" Plugin 'Vimjas/vim-python-pep8-indent'
" Plugin 'airblade/vim-gitgutter'
" Plugin 'amix/open_file_under_cursor.vim'
" Plugin 'amix/vim-zenroom2'
" Plugin 'chr4/nginx.vim'
" Plugin 'craigemery/vim-autotag'
" Plugin 'crusoexia/vim-monokai'
" Plugin 'farmergreg/vim-lastplace'
" Plugin 'garbas/vim-snipmate'
" Plugin 'groenewege/vim-less'
" Plugin 'honza/vim-snippets'
" Plugin 'hrsh7th/nvim-compe' 
" Plugin 'jalcine/cmake.vim'
" Plugin 'jlanzarotta/bufexplorer'
" Plugin 'kien/ctrlp.vim'
" Plugin 'mattn/vim-lsp-settings'
" Plugin 'maxbrunsfeld/vim-yankstack'
" Plugin 'michaeljsmith/vim-indent-object'
" Plugin 'mileszs/ack.vim'
" Plugin 'mru.vim'
" Plugin 'neovim/nvim-lspconfig'
" Plugin 'nvie/vim-flake8'
" Plugin 'pangloss/vim-javascript'
" Plugin 'prabirshrestha/async.vim'
" Plugin 'prabirshrestha/asyncomplete-lsp.vim'
" Plugin 'prabirshrestha/asyncomplete.vim'
" Plugin 'prabirshrestha/vim-lsp'
" Plugin 'scrooloose/nerdtree'
" Plugin 'scrooloose/syntastic'
" Plugin 'shougo/deoplete.nvim'
" Plugin 'skywind3000/gutentags_plus'
" Plugin 'terryma/vim-expand-region'
" Plugin 'terryma/vim-multiple-cursors'
" Plugin 'tomtom/tlib_vim'
" Plugin 'tpope/vim-commentary'
" Plugin 'tpope/vim-markdown'
" Plugin 'tpope/vim-repeat'
" Plugin 'tpope/vim-surround'
" Plugin 'valloric/youcompleteme'
" Plugin 'wvffle/vimterm'
"" " `:help :Glaive` for usage.
"" " let Vundle manage Vundle, required
"" Also add Glaive, which is used to configure codefmt's maktaba flags. See
"" Plugin 'neoclide/coc.nvim'
" Plugin 'SirVer/ultisnips'
" Plugin 'garbas/vim-snipmate'
" Plugin 'honza/vim-snippets'
" Plugin 'mattn/vim-lsp-settings'
" Plugin 'prabirshrestha/vim-lsp'
" Plugin 'MarcWeber/vim-addon-mw-utils'
" Plugin 'codegram/vim-codereview'
" Plugin 'grailbio/bazel-compilation-database'
" Plugin 'groenewege/vim-less'
" Plugin 'herringtondarkholme/yats.vim'
" Plugin 'jlanzarotta/bufexplorer'
" Plugin 'kien/ctrlp.vim'
" Plugin 'maksimr/vim-jsbeautify'
" Plugin 'pangloss/vim-javascript'
" Plugin 'rhysd/open-pdf.vim'
" Plugin 'rhysd/rust-doc.vim'
" Plugin 'roxma/nvim-yarp'
" Plugin 'roxma/vim-hug-neovim-rpc'
" Plugin 'tomtom/tlib_vim'
" Plugin 'wvffle/vimterm'
" Plugin 'xuhdev/vim-latex-live-preview'
Plugin  'tell-k/vim-autoflake'
Plugin '907th/vim-auto-save'
Plugin 'Vimjas/vim-python-pep8-indent'
Plugin 'VundleVim/Vundle.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'amix/open_file_under_cursor.vim'
Plugin 'amix/vim-zenroom2'
Plugin 'bazelbuild/vim-bazel'
Plugin 'chr4/nginx.vim'
Plugin 'dense-analysis/ale'
Plugin 'farmergreg/vim-lastplace'
Plugin 'google/vim-codefmt'
Plugin 'google/vim-glaive'
Plugin 'google/vim-maktaba'
Plugin 'greymd/oscyank.vim'
Plugin 'heavenshell/vim-pydocstring'
Plugin 'hushicai/tagbar-javascript.vim'
Plugin 'itchyny/lightline.vim'
Plugin 'jiangmiao/auto-pairs'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'junkblocker/patchreview-vim'
Plugin 'kabouzeid/nvim-lspinstall'
Plugin 'ludovicchabant/vim-gutentags'
Plugin 'majutsushi/tagbar'
Plugin 'matze/vim-move'
Plugin 'maxbrunsfeld/vim-yankstack'
Plugin 'michaeljsmith/vim-indent-object'
Plugin 'mikecoder/quickrun.vim'
Plugin 'mileszs/ack.vim'
Plugin 'morhetz/gruvbox'
Plugin 'mru.vim'
Plugin 'neoclide/coc.nvim'
Plugin 'octol/vim-cpp-enhanced-highlight'
Plugin 'prabirshrestha/async.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-rhubarb'
Plugin 'tpope/vim-surround'
Plugin 'zivyangll/git-blame.vim'
" Plugin 'kkoomen/vim-doge'

call vundle#end()            " required
filetype plugin indent on    " required

set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
source ~/.vim_runtime/my_configs.vim

